FROM golang:1.24 AS builder

WORKDIR /app

COPY go.mod go.sum ./
RUN go mod download

COPY . .
RUN go build -o webapi ./cmd/webapi

FROM debian:bookworm-slim
WORKDIR /app
COPY --from=builder /app/webapi .
EXPOSE 3000 4000
CMD ["./webapi"]
